# Base configuration preset for SS14 Persistence. On the official server this is loaded before persist.toml
# Related docs https://docs.spacestation14.com/en/general-development/tips/config-file-reference.html

[game]
hostname = "[NRP] Persistence Test Server"
desc = "Don't mind me, just using the base ConfigPreset!"
defaultpreset = "persist"
soft_max_players = 30
autosaveinterval = 60

[hub]
tags = "rp:none"

[infolinks]
bug_report = "https://github.com/ss14-art/mildew/issues"
discord    = "https://discord.gg/E2qapW2373"
github     = "https://github.com/ss14-art/mildew"

[server]
id = "Persistence"

[funkystation.reagent_fire]
puddle_damage_multiplier = 0.1

[funkystation.cpr]
rib_crack_damage = 20
rib_crack_pump = 10

[funkystation.defib]
revive_chance = 0.7
adrenaline_cost = 1
