using System.Linq;  
using Content.Client.UserInterface.Controls;  
using Content.Shared.Research.Components;  
using Robust.Client.AutoGenerated;  
using Robust.Client.UserInterface.Controls;  
using Robust.Client.UserInterface.XAML;  
  
namespace Content.Client.Research.UI;  
  
[GenerateTypedNameReferences]  
public sealed partial class ResearchServerMenu : FancyWindow  
{  
    public event Action<NetEntity>? OnClientEntryPressed;  
  
    public ResearchServerMenu()  
    {  
        RobustXamlLoader.Load(this);  
  
        ClientList.OnItemSelected += args =>  
        {  
            var item = ClientList[args.ItemIndex];  
            OnClientEntryPressed?.Invoke((NetEntity)item.Metadata!);  
        };  
    }  
  
    public void Update(ResearchServerBuiState state)  
    {  
        var items = new List<ItemList.Item>();  
        var ordered = state.Clients.OrderBy(t => t.SortKey).ThenBy(t => t.Entity.Id);  
        foreach (var (ent, _, _) in ordered)  
        {  
            items.Add(new ItemList.Item(ClientList) { Metadata = ent });  
        }  
  
        ClientList.SetItems(items, (item1, item2) =>  
        {  
            var ent1 = (NetEntity)item1.Metadata!;  
            var ent2 = (NetEntity)item2.Metadata!;  
            return ent1.CompareTo(ent2);  
        });  
  
        var entTextDict = state.Clients.ToDictionary(t => t.Entity, t => t.DisplayText);  
        using var enumerator = ClientList.GetEnumerator();  
        while (enumerator.MoveNext())  
        {  
            if (enumerator.Current.Metadata is not NetEntity ent)  
                continue;  
            if (entTextDict.TryGetValue(ent, out var text))  
                enumerator.Current.Text = text;  
        }  
    }  
}